const translations={
en:{
'nav.about':'About','nav.trips':'Monthly Trips','nav.pathshala':'Sunday Pathshala','nav.events':'Events','nav.knowledge':'Knowledge','nav.bhakti':'Bhakti','nav.darshan':'Darshan','nav.join':'Join Us',
'hero.eyebrow':'JIN SHASAN PRABHAVNA SANGH • KARNAL','hero.title':'A digital home for <em>Jain youth</em> in Karnal.','hero.lead':'Discover. Connect. Learn. Experience. Participate. Serve.','hero.text':'A community space for Jain darshan, yatras, knowledge, bhakti, events and seva — created to bring young Jains together.','hero.cta1':'Join the Community','hero.cta2':'Explore Bhakti','hero.cardLabel':'JIN DARSHAN','hero.cardText':'Faith • Community • Journey',
'about.eyebrow':'WHO WE ARE','about.title':'Building a connected Jain youth community.','about.p1':'Jain Youth Karnal is the public-facing youth identity of <strong>Jin Shasan Prabhavna Sangh Karnal</strong>. The initiative brings together young Jains through spirituality, Jain knowledge, temple visits, yatras, bhakti, community events and seva.','about.p2':'The website is designed to become a living archive and a community gateway — not simply an information page.',
'trips.eyebrow':'MONTHLY JAIN TRIPS','trips.title':'A year of journeys, darshan & memories.','trips.intro':"Jin Shasan Prabhavna Sangh's 2026 monthly trip journey across Jain destinations.",'trip.unspecified':'Mandir visited: Not specified','trip.visited':'Mandir visited:',
'path.eyebrow':'SUNDAY PATHSHALA','path.title':'Learn, grow & stay connected with Jain values.','path.text':'Sunday Pathshala is a regular learning space for the Jain community in Karnal — bringing children and young learners together for Jain knowledge, values, stories and sanskar.','path.every':'EVERY SUNDAY','path.p1t':'Jain Dharma','path.p1p':'Learn foundational Jain principles and teachings.','path.p2t':'Stories & Sanskar','path.p2p':'Build connection with Jain values through stories and activities.','path.p3t':'Community','path.p3p':'Learn together and grow as part of the Jain community.',
'events.eyebrow':'COMMUNITY CALENDAR','events.title':'Events & activities','events.c1t':'Religious Events','events.c1p':'Jain parvas, puja, bhakti and spiritual programmes.','events.c2t':'Youth Events','events.c2p':'Activities that bring Jain youth together through participation and connection.','events.c3t':'Cultural & Seva','events.c3p':'Community programmes, cultural activities and future seva initiatives.',
'knowledge.eyebrow':'JAIN KNOWLEDGE','knowledge.title':'Learn Jain Dharma, one story at a time.','knowledge.label':'Knowledge Hub','knowledge.k1t':'Tirthankaras','knowledge.k1p':'Profiles, teachings and important milestones.','knowledge.k2t':'Kalyanaks','knowledge.k2p':'Explore the five Kalyanaks and their significance.','knowledge.k3t':'Jain Places','knowledge.k3p':'Atishay Kshetras, Siddha Kshetras, Jinalayas and pilgrimage destinations.','knowledge.k4t':'Practices & Parvas','knowledge.k4p':'Jaap, Bhaktamar, puja, parvas and other Jain practices.',
'bhakti.eyebrow':'BHAKTI SANGEET','bhakti.title':'Bhajans to read, reflect on and sing.','bhakti.intro':'Original Hindi lyrics are preserved as provided. Use the language toggle to view an English meaning.','bhakti.label':'Bhakti Sangeet','bhakti.note':'<strong>Bhakti Sangeet</strong><br>More Jain bhajans and devotional content can be added here over time.',
'darshan.eyebrow':'JIN DARSHAN DIARIES','darshan.title':'Places of faith, captured with care.','darshan.intro':'Karnal Mandir darshan will have its own dedicated gallery, including up to eight images of the deities.','darshan.label':'Darshan • Architecture • Memories','darshan.karnalTitle':'Karnal Mandir • Deity Gallery','darshan.karnalText':'Eight image slots are prepared in assets/karnal-mandir/god-images/. Add files as god-01 through god-08 when ready.',
'join.eyebrow':'BECOME A PART','join.title':'Join Jain Youth Karnal.','join.text':"Whether you want to join a yatra, volunteer at an event, contribute content, participate in seva or simply stay connected — we'd love to hear from you.",'form.name':'Name','form.nameph':'Your name','form.email':'Email','form.emailph':'Your email','form.phone':'Phone','form.phoneph':'Your phone number','form.interest':'How would you like to participate?','form.opt1':'Jain Yatra','form.opt2':'Events','form.opt3':'Seva','form.opt4':'Jain Education','form.opt5':'Bhakti','form.opt6':'Content / Photography','form.opt7':'Volunteering','form.submit':'Connect With Us',
'footer.explore':'Explore','footer.connect':'Connect','footer.rights':'All rights reserved.'},
hi:{
'nav.about':'हमारे बारे में','nav.trips':'मासिक यात्राएँ','nav.pathshala':'रविवार पाठशाला','nav.events':'कार्यक्रम','nav.knowledge':'जैन ज्ञान','nav.bhakti':'भक्ति','nav.darshan':'जिन दर्शन','nav.join':'जुड़ें',
'hero.eyebrow':'जिन शासन प्रभावना संघ • करनाल','hero.title':'करनाल के <em>जैन युवाओं</em> का डिजिटल घर।','hero.lead':'जानें। जुड़ें। सीखें। अनुभव करें। सहभागी बनें। सेवा करें।','hero.text':'जिन दर्शन, यात्राओं, जैन ज्ञान, भक्ति, कार्यक्रमों और सेवा के लिए एक ऐसा समुदाय मंच, जो जैन युवाओं को साथ लाने के उद्देश्य से बनाया गया है।','hero.cta1':'समुदाय से जुड़ें','hero.cta2':'भक्ति देखें','hero.cardLabel':'जिन दर्शन','hero.cardText':'आस्था • समुदाय • यात्रा',
'about.eyebrow':'हम कौन हैं','about.title':'एक जुड़े हुए जैन युवा समुदाय का निर्माण।','about.p1':'जैन यूथ करनाल, <strong>जिन शासन प्रभावना संघ करनाल</strong> की युवा पहचान है। यह पहल आध्यात्मिकता, जैन ज्ञान, मंदिर दर्शन, यात्राओं, भक्ति, सामुदायिक कार्यक्रमों और सेवा के माध्यम से जैन युवाओं को जोड़ती है।','about.p2':'यह वेबसाइट केवल जानकारी का पृष्ठ नहीं, बल्कि एक जीवंत डिजिटल संग्रह और समुदाय से जुड़ने का माध्यम बनने के लिए तैयार की गई है।',
'trips.eyebrow':'मासिक जैन यात्राएँ','trips.title':'यात्राओं, जिन दर्शन और यादों से भरा एक वर्ष।','trips.intro':'जिन शासन प्रभावना संघ की 2026 की मासिक यात्राओं का जैन तीर्थों और दर्शनीय स्थलों का सफर।','trip.unspecified':'मंदिर दर्शन: उपलब्ध जानकारी नहीं','trip.visited':'मंदिर दर्शन:',
'path.eyebrow':'रविवार पाठशाला','path.title':'सीखें, बढ़ें और जैन मूल्यों से जुड़े रहें।','path.text':'रविवार पाठशाला करनाल के जैन समुदाय के लिए नियमित सीखने का मंच है, जहाँ बच्चे और युवा जैन ज्ञान, संस्कार, कथाओं और मूल्यों से जुड़ते हैं।','path.every':'हर रविवार','path.p1t':'जैन धर्म','path.p1p':'जैन धर्म के मूल सिद्धांतों और शिक्षाओं को जानें।','path.p2t':'कथाएँ और संस्कार','path.p2p':'कथाओं और गतिविधियों के माध्यम से जैन मूल्यों से जुड़ें।','path.p3t':'समुदाय','path.p3p':'साथ सीखें और जैन समुदाय के साथ आगे बढ़ें।',
'events.eyebrow':'सामुदायिक कैलेंडर','events.title':'कार्यक्रम और गतिविधियाँ','events.c1t':'धार्मिक कार्यक्रम','events.c1p':'जैन पर्व, पूजा, भक्ति और आध्यात्मिक कार्यक्रम।','events.c2t':'युवा कार्यक्रम','events.c2p':'ऐसी गतिविधियाँ जो सहभागिता और जुड़ाव के माध्यम से जैन युवाओं को साथ लाएँ।','events.c3t':'सांस्कृतिक एवं सेवा','events.c3p':'सामुदायिक कार्यक्रम, सांस्कृतिक गतिविधियाँ और भविष्य की सेवा पहल।',
'knowledge.eyebrow':'जैन ज्ञान','knowledge.title':'एक-एक कथा के माध्यम से जैन धर्म को जानें।','knowledge.label':'ज्ञान केंद्र','knowledge.k1t':'तीर्थंकर','knowledge.k1p':'तीर्थंकरों का परिचय, शिक्षाएँ और महत्वपूर्ण पड़ाव।','knowledge.k2t':'कल्याणक','knowledge.k2p':'पाँच कल्याणकों और उनके महत्व को जानें।','knowledge.k3t':'जैन तीर्थ एवं स्थान','knowledge.k3p':'अतिशय क्षेत्र, सिद्ध क्षेत्र, जिनालय और तीर्थयात्रा के प्रमुख स्थान।','knowledge.k4t':'प्रथाएँ एवं पर्व','knowledge.k4p':'जाप, भक्तामर, पूजा, पर्व और अन्य जैन धार्मिक प्रथाएँ।',
'bhakti.eyebrow':'भक्ति संगीत','bhakti.title':'भजनों को पढ़ें, मनन करें और गाएँ।','bhakti.intro':'मूल हिंदी बोल जैसा उपलब्ध कराया गया है वैसा ही सुरक्षित रखा गया है। अंग्रेज़ी अर्थ देखने के लिए भाषा बदलें।','bhakti.label':'भक्ति संगीत','bhakti.note':'<strong>भक्ति संगीत</strong><br>समय के साथ यहाँ और जैन भजन एवं भक्तिमय सामग्री जोड़ी जा सकती है।',
'darshan.eyebrow':'जिन दर्शन डायरी','darshan.title':'आस्था के स्थान, श्रद्धा के साथ संजोए हुए।','darshan.intro':'करनाल मंदिर दर्शन के लिए अलग गैलरी तैयार है, जिसमें तीर्थंकर प्रतिमाओं की आठ तक तस्वीरें जोड़ी जा सकती हैं।','darshan.label':'दर्शन • स्थापत्य • यादें','darshan.karnalTitle':'करनाल मंदिर • जिन प्रतिमा गैलरी','darshan.karnalText':'आठ तस्वीरों के लिए assets/karnal-mandir/god-images/ में स्थान तैयार है। तस्वीरों के नाम god-01 से god-08 रखें।',
'join.eyebrow':'हमसे जुड़ें','join.title':'जैन यूथ करनाल से जुड़ें।','join.text':'चाहे आप यात्रा से जुड़ना चाहते हों, किसी कार्यक्रम में स्वयंसेवा करना चाहते हों, सामग्री में योगदान देना चाहते हों, सेवा में सहभागी बनना चाहते हों या केवल जुड़े रहना चाहते हों — हम आपसे जुड़कर खुशी होगी।','form.name':'नाम','form.nameph':'अपना नाम','form.email':'ईमेल','form.emailph':'अपना ईमेल','form.phone':'मोबाइल नंबर','form.phoneph':'अपना मोबाइल नंबर','form.interest':'आप किस रूप में सहभागी बनना चाहेंगे?','form.opt1':'जैन यात्रा','form.opt2':'कार्यक्रम','form.opt3':'सेवा','form.opt4':'जैन शिक्षा','form.opt5':'भक्ति','form.opt6':'सामग्री / फोटोग्राफी','form.opt7':'स्वयंसेवा','form.submit':'हमसे जुड़ें',
'footer.explore':'अन्वेषण करें','footer.connect':'संपर्क करें','footer.rights':'सर्वाधिकार सुरक्षित।'}
};

const menuToggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#nav');
if(menuToggle&&nav){menuToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuToggle.setAttribute('aria-expanded','false');}));}

const siteLangs=document.querySelectorAll('.site-lang');
function setLanguage(lang){const t=translations[lang]||translations.en;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key]!==undefined)el.innerHTML=t[key];});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder;if(t[key]!==undefined)el.placeholder=t[key];});siteLangs.forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.documentElement.lang=lang;localStorage.setItem('jyk-language',lang);}
siteLangs.forEach(btn=>btn.addEventListener('click',()=>setLanguage(btn.dataset.lang)));
setLanguage(localStorage.getItem('jyk-language')||'en');
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();


// Optional bhajan media: add an audio URL in data-audio-url on the bhajan card link.
document.querySelectorAll('.audio-link[data-audio-url]').forEach(link=>{
  const url=(link.dataset.audioUrl||'').trim();
  if(url){ link.href=url; link.target='_blank'; link.rel='noopener'; link.classList.remove('disabled'); link.removeAttribute('aria-disabled'); }
});
